### ISSUE TITLE
Add AssemblyInfo

### ISSUE THREAD

**Issue by Tarmil** [intellifactory/Bolero#2]
In particular the AssemblyVersion is not set from the package version, and instead is the default 1.0.0.0.

**Comment by StefanBelo** [comment]
Did you really add: AssemblyInfo.fs

Unable to open 'AssemblyInfo.fs': File not found (file:///d:/Samples/Bolero-master/build/AssemblyInfo.fs).

when trying to build, above error message is showed.

**Comment by Tarmil** [comment]
AssemblyInfo.fs is generated by the FAKE script, so you need to run `.\build.cmd` or `./build.sh` (depending on your platform) before opening the solution in an IDE.
